# espanso match file

# For a complete introduction, visit the official docs at: https://espanso.org/docs/

# You can use this file to define the base matches (aka snippets)
# that will be available in every application when using espanso.

# Matches are substitution rules: when you type the "trigger" string
# it gets replaced by the "replace" string.
matches:
  # NOTE: espanso uses YAML to define matches, so pay attention to the indentation!


  # But matches can also be dynamic:

  # Print the current date
  - regex: "(?i):date:"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%Y-%m-%d"

  # Print comment signature with date
  - regex: "(?i):lp:"
    replace: "{{signature}}"
    vars:
      - name: signature
        type: date
        params:
          format: "LP %Y-%m-%d"

  # Php error_log with print_r
  - triggers: 
    - ":print_r:"
    - ":print:"
    replace: "error_log(\"LP \" . print_r($|$, true));"

  # Print markdown code triple ````
  - regex: "(?i):code:"
    replace: "\u0060\u0060\u0060$|$\n\u0060\u0060\u0060"

  # alias shorthands for different types of markdown codeblocks
  - regex: "(?i):sql:"
    replace: "\u0060\u0060\u0060sql\n$|$\n\u0060\u0060\u0060"
  - regex: "(?i):php:"
    replace: "\u0060\u0060\u0060php\n$|$\n\u0060\u0060\u0060"
  - regex: "(?i):js:"
    replace: "\u0060\u0060\u0060js\n$|$\n\u0060\u0060\u0060"
  - regex: "(?i):ts:"
    replace: "\u0060\u0060\u0060ts\n$|$\n\u0060\u0060\u0060"
  - regex: "(?i):html:"
    replace: "\u0060\u0060\u0060html\n$|$\n\u0060\u0060\u0060"
  - regex: "(?i):python:"
    replace: "\u0060\u0060\u0060python\n$|$\n\u0060\u0060\u0060"

  # And much more! For more information, visit the docs: https://espanso.org/docs/
